//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodReviewWeb.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string ID { get; set; }
        public string PostID { get; set; }
        public string UserID { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Post Post { get; set; }
    }
}
